### ISSUE TITLE
"harness-apply" command asks for user input with values already present on YAML.

### ISSUE THREAD

**Issue by Debanitrkl** [harness/harness-cli#31]
## Summary

`harness` Cli is asking for text input for the `delegate-name` for creating kubernetes connector as show below, even when the `delegateSelectors:` had delegate name mentioned 

```                   
Trying to create or update connector using the yaml= harnesscd-example-apps/guestbook/harnesscd-pipeline/kubernetes-connector.yml
? Enter valid delegate name: delegate-deba-demo
```
## Environment

Harness Cli Version: `v0.0.10-alpha`
OS: `Mac M1 Pro`

## Steps To Reproduce
1. Use the connector YAML with pre-filled delegate name under `delegateSelectors:` as follows:
```
connector:
  name: harness_k8sconnecto
  identifier: harnessk8sconnecto
  description: ""
  orgIdentifier: default
  projectIdentifier: communityeng
  type: K8sCluster
  spec:
    credential:
      type: InheritFromDelegate
    delegateSelectors:
      - Delegate_Name

```

2. Use apply command to create the connector as follows:

```
harness connector --file <file-path of the connector yaml> apply
```

## Expected Results

```
deba@Debabrata Panigrahi harness-cli %  harness connector --file harnesscd-example-apps/guestbook/harnesscd-pipeline/kubernetes-connector.yml apply     
Trying to create or update connector using the yaml= harnesscd-example-apps/guestbook/harnesscd-pipeline/kubernetes-connector.yml
ERRO[2023-07-25T15:27:35+05:30] Connector with identifier [harnessk8sconnecto] not found in project [communityeng] and org [default]. 
Creating connector with id:  harnessk8sconnecto
Successfully created connector with id= harnessk8sconnecto
```

## Actual Results

```
deba@Debabrata Panigrahi harness-cli %  harness connector --file harnesscd-example-apps/guestbook/harnesscd-pipeline/kubernetes-connector.yml apply                         
Trying to create or update connector using the yaml= harnesscd-example-apps/guestbook/harnesscd-pipeline/kubernetes-connector.yml
? Enter valid delegate name: delegate-deba-demo
ERRO[2023-07-25T15:27:35+05:30] Connector with identifier [harnessk8sconnecto] not found in project [communityeng] and org [default]. 
Creating connector with id:  harnessk8sconnecto
Successfully created connector with id= harnessk8sconnecto
```
